server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: sifre123
    url: jdbc:mysql://localhost:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
